### ISSUE TITLE
Sử dụng matrix strategy để giảm thời gian chạy github actions

### ISSUE THREAD

**Issue by hoangnguyennn** [hoangnguyennn/hn-elements#7]
### Tổng quan

Lint và test có flow gần như giống nhau. Có thể sử dụng matrix strategy để giảm thời gian chạy github actions.

### Giải pháp khả thi

Xóa 2 flows như hiện tại và thêm flow mới như sau:

```yml
name: lint-and-test

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ${{ matrix.task }}
        run: bun run ${{ matrix.task }}
```

### Ngữ cảnh

Lint và test flows đang trùng lặp nhiều
